/**
 * Blog post data — 35 auto-generated SEO topical articles.
 *
 * The 35 SEO topical articles (Tier 2 cluster hubs) live in `blog.seo-pack.ts`
 * and are generated by `_build/convert_to_blogpost.py` from the SEJ topical
 * pack. They are spread into BLOG_POSTS below.
 *
 * To add a hand-written post, append a BlogPost object to BLOG_POSTS above
 * the SEO_PACK spread. The dynamic route at /blog/[slug] reads from this file.
 */

import { BLOG_POSTS_SEO_PACK } from "./blog.seo-pack";

export interface BlogPost {
  slug: string;
  title: string;
  description: string;
  category: "Original research" | "Playbooks" | "Case studies" | "Industry news";
  author: string;        // matches TEAM slug in /about (e.g. "hammad-abid")
  authorTitle: string;
  date: string;          // ISO YYYY-MM-DD
  readMinutes: number;
  /** Hero image, can be null for now (we ship without one). */
  hero?: { src: string; alt: string } | null;
  /** Tags shown on the detail page and as filters on the list. */
  tags: string[];
  /** Whether to show the lead-magnet CTA at the bottom (PDF / email gate). */
  gatedCta: boolean;
  /** Optional sub-CTA: subscribe to monthly transparency report. */
  subscribeCta: boolean;
  /** Body. Each block is rendered with a sensible default style. */
  body: BlogBlock[];
  /** Optional related slugs. */
  relatedSlugs?: string[];
}

export type BlogBlock =
  | { type: "p"; text: string }
  | { type: "h2"; text: string }
  | { type: "h3"; text: string }
  | { type: "ul"; items: string[] }
  | { type: "ol"; items: string[] }
  | { type: "quote"; text: string; cite?: string }
  | { type: "callout"; tone: "tip" | "warning" | "insight"; text: string }
  | { type: "stats"; items: { value: string; label: string }[] }
  | { type: "code"; language?: string; text: string }
  | { type: "table"; head: string[]; rows: string[][] }
  | { type: "toc" };

export const BLOG_POSTS: BlogPost[] = [...BLOG_POSTS_SEO_PACK];

export const BLOG_POST_BY_SLUG: Record<string, BlogPost> = Object.fromEntries(
  BLOG_POSTS.map((p) => [p.slug, p])
);
